version: "3"
services:
  cmd:
    container_name: ga-api
    build:
      context: ./api
    ports:
      - 8000:8000
    networks:
      - frontend
      - backend

  database:
    container_name: ga-database
    build:
      context: ./database
    ports:
      - 3306:3306
    networks:
      - backend

  web:
    container_name: ga-client
    build:
      context: ./client
    ports:
      - 4000:4000
    networks:
      - frontend
networks:
  backend:
  frontend: