version: "3.3"
services:
  cmd:
    container_name: ga-api
    build:
      context: api
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - database

  database:
    container_name: ga-database
    build:
      context: database
    ports:
      - "3300:3306"
    networks:
      - backend

  web:
    container_name: ga-client
    build:
      context: client
    ports:
      - "4000:80"
    networks:
      - backend

networks:
  backend: